export const FOOTBALL_SCHEDULE_DATA = [
  {
    series: "FIFA World Cup 2026 - Group Stage",
    period: "June 11 - June 27, 2026",
    matches: [
      { event: "Match 1: Mexico vs South Africa (Group A)", date: "June 11, 2026", venue: "Azteca Stadium, Mexico City", time: "12:00 ET" },
      { event: "Match 2: Canada vs Bosnia and Herzegovina (Group B)", date: "June 12, 2026", venue: "BMO Field, Toronto", time: "15:00 ET" },
      { event: "Match 3: USA vs Paraguay (Group D)", date: "June 12, 2026", venue: "SoFi Stadium, Los Angeles", time: "18:00 ET" },
      { event: "Match 4: Haiti vs Scotland (Group C)", date: "June 13, 2026", venue: "BC Place, Vancouver", time: "12:00 ET" },
      { event: "Match 5: Germany vs Ghana (Group E)", date: "June 13, 2026", venue: "Gillette Stadium, Boston", time: "15:00 ET" },
      { event: "Match 6: France vs Senegal (Group F)", date: "June 14, 2026", venue: "Lincoln Financial Field, Philadelphia", time: "12:00 ET" },
      { event: "Match 7: Argentina vs Ivory Coast (Group G)", date: "June 14, 2026", venue: "Hard Rock Stadium, Miami", time: "18:00 ET" },
      { event: "Match 8: England vs Egypt (Group H)", date: "June 15, 2026", venue: "Mercedes-Benz Stadium, Atlanta", time: "12:00 ET" },
      { event: "Match 9: Portugal vs Nigeria (Group I)", date: "June 15, 2026", venue: "Lumen Field, Seattle", time: "15:00 ET" },
      { event: "Match 10: Belgium vs Panama (Group J)", date: "June 16, 2026", venue: "Levi's Stadium, San Francisco", time: "12:00 ET" },
      { event: "Match 11: Italy vs Jamaica (Group K)", date: "June 16, 2026", venue: "NRG Stadium, Houston", time: "18:00 ET" },
      { event: "Match 12: Denmark vs Costa Rica (Group L)", date: "June 17, 2026", venue: "AT&T Stadium, Dallas", time: "15:00 ET" },
      { event: "Match 13: Korea Republic vs Czechia (Group A)", date: "June 17, 2026", venue: "Akron Stadium, Guadalajara", time: "12:00 ET" },
      { event: "Match 14: Spain vs Algeria (Group B)", date: "June 18, 2026", venue: "BC Place, Vancouver", time: "15:00 ET" },
      { event: "Match 15: Brazil vs Morocco (Group C)", date: "June 18, 2026", venue: "SoFi Stadium, Los Angeles", time: "18:00 ET" },
      { event: "Match 16: Australia vs Turkey (Group D)", date: "June 19, 2026", venue: "Lumen Field, Seattle", time: "12:00 ET" },
      { event: "Match 17: Japan vs Norway (Group E)", date: "June 19, 2026", venue: "Lincoln Financial Field, Philadelphia", time: "15:00 ET" },
      { event: "Match 18: Ecuador vs Qatar (Group F)", date: "June 20, 2026", venue: "Hard Rock Stadium, Miami", time: "12:00 ET" },
      { event: "Match 19: Netherlands vs Uzbekistan (Group G)", date: "June 20, 2026", venue: "Gillette Stadium, Boston", time: "18:00 ET" },
      { event: "Match 20: Colombia vs New Zealand (Group H)", date: "June 21, 2026", venue: "NRG Stadium, Houston", time: "15:00 ET" },
      { event: "Match 21: Uruguay vs Iran (Group I)", date: "June 21, 2026", venue: "AT&T Stadium, Dallas", time: "12:00 ET" },
      { event: "Match 22: Croatia vs Saudi Arabia (Group J)", date: "June 22, 2026", venue: "BMO Field, Toronto", time: "18:00 ET" },
      { event: "Match 23: Switzerland vs Jordan (Group K)", date: "June 22, 2026", venue: "Mercedes-Benz Stadium, Atlanta", time: "15:00 ET" },
      { event: "Match 24: Austria vs Tunisia (Group L)", date: "June 23, 2026", venue: "MetLife Stadium, East Rutherford", time: "12:00 ET" },
      { event: "Match 25: Mexico vs Korea Republic (Group A)", date: "June 23, 2026", venue: "Azteca Stadium, Mexico City", time: "18:00 ET" },
      { event: "Match 26: Canada vs Spain (Group B)", date: "June 24, 2026", venue: "BC Place, Vancouver", time: "15:00 ET" },
      { event: "Match 27: Haiti vs Brazil (Group C)", date: "June 24, 2026", venue: "SoFi Stadium, Los Angeles", time: "12:00 ET" },
      { event: "Match 28: USA vs Australia (Group D)", date: "June 25, 2026", venue: "Lumen Field, Seattle", time: "18:00 ET" },
      { event: "Match 29: Germany vs Japan (Group E)", date: "June 25, 2026", venue: "Gillette Stadium, Boston", time: "15:00 ET" },
      { event: "Match 30: France vs Ecuador (Group F)", date: "June 26, 2026", venue: "Hard Rock Stadium, Miami", time: "12:00 ET" },
      { event: "Match 31: Argentina vs Netherlands (Group G)", date: "June 26, 2026", venue: "Lincoln Financial Field, Philadelphia", time: "18:00 ET" },
      { event: "Match 32: England vs Colombia (Group H)", date: "June 27, 2026", venue: "NRG Stadium, Houston", time: "15:00 ET" },
      { event: "Match 33: Portugal vs Uruguay (Group I)", date: "June 27, 2026", venue: "AT&T Stadium, Dallas", time: "12:00 ET" },
      { event: "Match 34: Belgium vs Croatia (Group J)", date: "June 28, 2026", venue: "Mercedes-Benz Stadium, Atlanta", time: "18:00 ET" },
      { event: "Match 35: Italy vs Switzerland (Group K)", date: "June 28, 2026", venue: "Levi's Stadium, San Francisco", time: "15:00 ET" },
      { event: "Match 36: Denmark vs Austria (Group L)", date: "June 29, 2026", venue: "MetLife Stadium, East Rutherford", time: "12:00 ET" },
    ],
  },
  {
    series: "FIFA World Cup 2026 - Knockout Stage",
    period: "June 28 - July 19, 2026",
    matches: [
      { event: "Round of 32: Mexico vs Spain", date: "June 28, 2026", venue: "SoFi Stadium, Los Angeles", time: "15:00 ET" },
      { event: "Round of 32: Brazil vs USA", date: "June 29, 2026", venue: "Gillette Stadium, Boston", time: "18:00 ET" },
      { event: "Round of 32: Germany vs Senegal", date: "June 30, 2026", venue: "BC Place, Vancouver", time: "12:00 ET" },
      { event: "Round of 32: Argentina vs England", date: "June 30, 2026", venue: "Akron Stadium, Guadalajara", time: "18:00 ET" },
      { event: "Round of 32: France vs Japan", date: "July 01, 2026", venue: "BMO Field, Toronto", time: "15:00 ET" },
      { event: "Round of 32: Portugal vs Belgium", date: "July 01, 2026", venue: "Levi's Stadium, San Francisco", time: "18:00 ET" },
      { event: "Round of 32: Netherlands vs Uruguay", date: "July 02, 2026", venue: "Mercedes-Benz Stadium, Atlanta", time: "12:00 ET" },
      { event: "Round of 32: Italy vs Denmark", date: "July 02, 2026", venue: "NRG Stadium, Houston", time: "15:00 ET" },
      { event: "Round of 16: Mexico vs Brazil", date: "July 04, 2026", venue: "Lincoln Financial Field, Philadelphia", time: "18:00 ET" },
      { event: "Round of 16: Argentina vs France", date: "July 05, 2026", venue: "AT&T Stadium, Dallas", time: "15:00 ET" },
      { event: "Round of 16: Germany vs Portugal", date: "July 05, 2026", venue: "Hard Rock Stadium, Miami", time: "12:00 ET" },
      { event: "Round of 16: England vs Netherlands", date: "July 06, 2026", venue: "Lumen Field, Seattle", time: "18:00 ET" },
      { event: "Round of 16: Spain vs Italy", date: "July 07, 2026", venue: "BC Place, Vancouver", time: "15:00 ET" },
      { event: "Quarter-Final: Brazil vs Argentina", date: "July 09, 2026", venue: "Gillette Stadium, Boston", time: "18:00 ET" },
      { event: "Quarter-Final: France vs Portugal", date: "July 10, 2026", venue: "SoFi Stadium, Los Angeles", time: "15:00 ET" },
      { event: "Quarter-Final: England vs Spain", date: "July 11, 2026", venue: "Hard Rock Stadium, Miami", time: "12:00 ET" },
      { event: "Quarter-Final: Germany vs Netherlands", date: "July 11, 2026", venue: "Arrowhead Stadium, Kansas City", time: "18:00 ET" },
      { event: "Semi-Final: Argentina vs France", date: "July 14, 2026", venue: "AT&T Stadium, Dallas", time: "15:00 ET" },
      { event: "Semi-Final: Brazil vs England", date: "July 15, 2026", venue: "Mercedes-Benz Stadium, Atlanta", time: "18:00 ET" },
      { event: "Third Place Play-off: France vs England", date: "July 18, 2026", venue: "Hard Rock Stadium, Miami", time: "15:00 ET" },
      { event: "FIFA World Cup Final: Argentina vs Brazil", date: "July 19, 2026", venue: "MetLife Stadium, East Rutherford", time: "15:00 ET" },
    ],
  },
  {
    series: "Premier League 2026/27 - Key Fixtures",
    period: "Aug 2026 - May 2027",
    matches: [
      { event: "Opening Weekend: Man City vs Liverpool", date: "Aug 15, 2026", venue: "Etihad Stadium, Manchester", time: "17:30 IST" },
      { event: "London Derby: Arsenal vs Chelsea", date: "Aug 29, 2026", venue: "Emirates Stadium, London", time: "20:30 IST" },
      { event: "Manchester Derby: Man Utd vs Man City", date: "Sept 12, 2026", venue: "Old Trafford, Manchester", time: "18:30 IST" },
    ],
  },
];
