import { createFileRoute } from '@tanstack/react-router'

const ISSUER = "https://mahadevbookss.com"

const config = {
  issuer: ISSUER,
  authorization_endpoint: `${ISSUER}/oauth/authorize`,
  token_endpoint: `${ISSUER}/oauth/token`,
  userinfo_endpoint: `${ISSUER}/oauth/userinfo`,
  jwks_uri: `${ISSUER}/.well-known/jwks.json`,
  registration_endpoint: `${ISSUER}/oauth/register`,
  revocation_endpoint: `${ISSUER}/oauth/revoke`,
  introspection_endpoint: `${ISSUER}/oauth/introspect`,
  end_session_endpoint: `${ISSUER}/oauth/logout`,
  device_authorization_endpoint: `${ISSUER}/oauth/device`,
  scopes_supported: ["openid", "profile", "email", "offline_access", "address", "phone"],
  response_types_supported: [
    "code",
    "token",
    "id_token",
    "code id_token",
    "code token",
    "id_token token",
    "code id_token token",
  ],
  response_modes_supported: ["query", "fragment", "form_post"],
  grant_types_supported: [
    "authorization_code",
    "refresh_token",
    "client_credentials",
    "urn:ietf:params:oauth:grant-type:device_code",
    "urn:ietf:params:oauth:grant-type:jwt-bearer",
  ],
  subject_types_supported: ["public", "pairwise"],
  id_token_signing_alg_values_supported: ["RS256", "RS384", "RS512", "ES256", "ES384", "PS256"],
  id_token_encryption_alg_values_supported: ["RSA-OAEP", "RSA-OAEP-256"],
  id_token_encryption_enc_values_supported: ["A128CBC-HS256", "A256GCM"],
  userinfo_signing_alg_values_supported: ["RS256", "ES256", "none"],
  request_object_signing_alg_values_supported: ["RS256", "ES256", "none"],
  token_endpoint_auth_methods_supported: [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt",
    "none",
  ],
  token_endpoint_auth_signing_alg_values_supported: ["RS256", "ES256"],
  revocation_endpoint_auth_methods_supported: ["client_secret_basic", "client_secret_post"],
  introspection_endpoint_auth_methods_supported: ["client_secret_basic", "client_secret_post"],
  code_challenge_methods_supported: ["S256", "plain"],
  claims_supported: [
    "sub",
    "iss",
    "aud",
    "exp",
    "iat",
    "auth_time",
    "nonce",
    "acr",
    "amr",
    "azp",
    "email",
    "email_verified",
    "name",
    "given_name",
    "family_name",
    "preferred_username",
    "picture",
    "locale",
    "updated_at",
  ],
  claim_types_supported: ["normal"],
  claims_parameter_supported: true,
  request_parameter_supported: true,
  request_uri_parameter_supported: true,
  require_request_uri_registration: false,
  display_values_supported: ["page", "popup", "touch", "wap"],
  ui_locales_supported: ["en", "en-IN", "hi"],
  acr_values_supported: ["urn:mace:incommon:iap:silver", "urn:mace:incommon:iap:bronze"],
  service_documentation: `${ISSUER}/.well-known/agents.json`,
  op_policy_uri: `${ISSUER}/policies`,
  op_tos_uri: `${ISSUER}/terms-conditions`,
  frontchannel_logout_supported: true,
  frontchannel_logout_session_supported: true,
  backchannel_logout_supported: true,
  backchannel_logout_session_supported: true,
  tls_client_certificate_bound_access_tokens: false,
  authorization_response_iss_parameter_supported: true,
  mtls_endpoint_aliases: {
    token_endpoint: `${ISSUER}/oauth/mtls/token`,
    revocation_endpoint: `${ISSUER}/oauth/mtls/revoke`,
    introspection_endpoint: `${ISSUER}/oauth/mtls/introspect`,
  },
}

export const Route = createFileRoute('/.well-known/openid-configuration')({
  server: {
    handlers: {
      GET: async () =>
        new Response(JSON.stringify(config, null, 2), {
          headers: {
            'Content-Type': 'application/json; charset=utf-8',
            'Cache-Control': 'public, max-age=3600',
            'Access-Control-Allow-Origin': '*',
          },
        }),
    },
  },
})
