import { useSuspenseQuery } from "@tanstack/react-query";
import { Sparkles, Check } from "lucide-react";
import { aiOverviewQueryOptions } from "@/lib/ai-overview.functions";

export function AiOverviewSection() {
  const { data } = useSuspenseQuery(aiOverviewQueryOptions);

  return (
    <section className="mx-auto max-w-7xl px-6 py-16">
      <div
        className="relative overflow-hidden rounded-3xl border border-border/60 bg-card p-8 md:p-12"
        style={{ boxShadow: "var(--shadow-glow-secondary)" }}
      >
        <div
          className="pointer-events-none absolute -top-24 -right-24 h-64 w-64 rounded-full opacity-30 blur-3xl"
          style={{ background: "var(--gradient-hero)" }}
          aria-hidden
        />
        <div className="relative grid gap-8 md:grid-cols-[minmax(0,1fr)_auto] md:items-start">
          <div className="min-w-0">
            <span className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.25em] text-primary">
              <Sparkles className="h-3.5 w-3.5" />
              AI Overview
            </span>
            <h2 className="mt-4 text-2xl font-black uppercase leading-tight text-foreground md:text-3xl">
              What is Sprinters, in one glance?
            </h2>
            <p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground md:text-lg">
              {data.summary}
            </p>
            <p className="mt-3 text-[11px] uppercase tracking-wider text-muted-foreground/70">
              Generated by Lovable AI
            </p>
          </div>
          <ul className="grid w-full max-w-md gap-2 rounded-2xl border border-border/50 bg-background/60 p-5 backdrop-blur">
            {data.highlights.map((h) => (
              <li key={h} className="flex items-start gap-2 text-sm text-foreground/90">
                <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                <span>{h}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
