/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Wpl2026BettingRouteImport } from './routes/wpl-2026-betting'
import { Route as WithdrawalDelayRouteImport } from './routes/withdrawal-delay'
import { Route as WhyChooseCricbet99RouteImport } from './routes/why-choose-cricbet99'
import { Route as WhatsappSupportRouteImport } from './routes/whatsapp-support'
import { Route as WhatsappNumberRouteImport } from './routes/whatsapp-number'
import { Route as WhatIsCricbet99RouteImport } from './routes/what-is-cricbet99'
import { Route as TrustedBettingIdProviderRouteImport } from './routes/trusted-betting-id-provider'
import { Route as TrustedBettingAgentRouteImport } from './routes/trusted-betting-agent'
import { Route as TransactionLimitsRouteImport } from './routes/transaction-limits'
import { Route as TodaysBestOddsRouteImport } from './routes/todays-best-odds'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TennisRouteImport } from './routes/tennis'
import { Route as TelegramChannelRouteImport } from './routes/telegram-channel'
import { Route as T20WorldCupBettingRouteImport } from './routes/t20-world-cup-betting'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SportsIdRouteImport } from './routes/sports-id'
import { Route as SportsBettingRouteImport } from './routes/sports-betting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReferralCodeRouteImport } from './routes/referral-code'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as OnlineBettingRouteImport } from './routes/online-betting'
import { Route as LoginIssuesRouteImport } from './routes/login-issues'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycPolicyRouteImport } from './routes/kyc-policy'
import { Route as KabaddiRouteImport } from './routes/kabaddi'
import { Route as IsCricbet99SafeRouteImport } from './routes/is-cricbet99-safe'
import { Route as IsCricbet99RealRouteImport } from './routes/is-cricbet99-real'
import { Route as IsCricbet99LegalRouteImport } from './routes/is-cricbet99-legal'
import { Route as IplBettingRouteImport } from './routes/ipl-betting'
import { Route as Ipl2026CalendarRouteImport } from './routes/ipl-2026-calendar'
import { Route as IndianCardGamesRouteImport } from './routes/indian-card-games'
import { Route as HowToWithdrawRouteImport } from './routes/how-to-withdraw'
import { Route as HowToDepositRouteImport } from './routes/how-to-deposit'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HorseRacingRouteImport } from './routes/horse-racing'
import { Route as HighOddsBettingStrategyRouteImport } from './routes/high-odds-betting-strategy'
import { Route as FootballRouteImport } from './routes/football'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as EsportsRouteImport } from './routes/esports'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DepositIssuesRouteImport } from './routes/deposit-issues'
import { Route as DemoIdRouteImport } from './routes/demo-id'
import { Route as CricketRouteImport } from './routes/cricket'
import { Route as Cricbet99VsSkyexchange247RouteImport } from './routes/cricbet99-vs-skyexchange247'
import { Route as Cricbet99VsReddybookRouteImport } from './routes/cricbet99-vs-reddybook'
import { Route as Cricbet99VsMahavirBookRouteImport } from './routes/cricbet99-vs-mahavir-book'
import { Route as Cricbet99VsLotus365RouteImport } from './routes/cricbet99-vs-lotus365'
import { Route as Cricbet99VsLaser247RouteImport } from './routes/cricbet99-vs-laser247'
import { Route as Cricbet99VsGold365RouteImport } from './routes/cricbet99-vs-gold365'
import { Route as Cricbet99VsFairdealRouteImport } from './routes/cricbet99-vs-fairdeal'
import { Route as Cricbet99VsDiamondExchangeRouteImport } from './routes/cricbet99-vs-diamond-exchange'
import { Route as Cricbet99Vs11xplayRouteImport } from './routes/cricbet99-vs-11xplay'
import { Route as Cricbet99IdRouteImport } from './routes/cricbet99-id'
import { Route as Cricbet99AppRouteImport } from './routes/cricbet99-app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ChampionsTrophyBettingRouteImport } from './routes/champions-trophy-betting'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BonusIssuesRouteImport } from './routes/bonus-issues'
import { Route as BonusRouteImport } from './routes/bonus'
import { Route as BigWinStoriesRouteImport } from './routes/big-win-stories'
import { Route as BettingGuidesRouteImport } from './routes/betting-guides'
import { Route as BecomeAgentRouteImport } from './routes/become-agent'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as AllLinksRouteImport } from './routes/all-links'
import { Route as AccountBlockedRouteImport } from './routes/account-blocked'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as MatchesSlugRouteImport } from './routes/matches.$slug'
import { Route as CaseStudiesTossMarket10MinuteProfitRouteImport } from './routes/case-studies.toss-market-10-minute-profit'
import { Route as CaseStudiesSmallBudgetBettingStrategyRouteImport } from './routes/case-studies.small-budget-betting-strategy'
import { Route as CaseStudiesLiveBetting3xReturnsRouteImport } from './routes/case-studies.live-betting-3x-returns'
import { Route as CaseStudiesIpl5000To25000ProfitRouteImport } from './routes/case-studies.ipl-5000-to-25000-profit'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BettingGuidesHowToSetBettingLimitsRouteImport } from './routes/betting-guides.how-to-set-betting-limits'
import { Route as BettingGuidesHowToPlaceALiveBetRouteImport } from './routes/betting-guides.how-to-place-a-live-bet'
import { Route as BettingGuidesHowToPlaceACricketBetRouteImport } from './routes/betting-guides.how-to-place-a-cricket-bet'
import { Route as BettingGuidesHowToBetOnTossMarketRouteImport } from './routes/betting-guides.how-to-bet-on-toss-market'
import { Route as BettingGuidesHowToBetOnSessionBettingRouteImport } from './routes/betting-guides.how-to-bet-on-session-betting'
import { Route as BettingGuidesHowBookmakersMakeMoneyRouteImport } from './routes/betting-guides.how-bookmakers-make-money'

const Wpl2026BettingRoute = Wpl2026BettingRouteImport.update({
  id: '/wpl-2026-betting',
  path: '/wpl-2026-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalDelayRoute = WithdrawalDelayRouteImport.update({
  id: '/withdrawal-delay',
  path: '/withdrawal-delay',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseCricbet99Route = WhyChooseCricbet99RouteImport.update({
  id: '/why-choose-cricbet99',
  path: '/why-choose-cricbet99',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappSupportRoute = WhatsappSupportRouteImport.update({
  id: '/whatsapp-support',
  path: '/whatsapp-support',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappNumberRoute = WhatsappNumberRouteImport.update({
  id: '/whatsapp-number',
  path: '/whatsapp-number',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsCricbet99Route = WhatIsCricbet99RouteImport.update({
  id: '/what-is-cricbet99',
  path: '/what-is-cricbet99',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedBettingIdProviderRoute =
  TrustedBettingIdProviderRouteImport.update({
    id: '/trusted-betting-id-provider',
    path: '/trusted-betting-id-provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustedBettingAgentRoute = TrustedBettingAgentRouteImport.update({
  id: '/trusted-betting-agent',
  path: '/trusted-betting-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionLimitsRoute = TransactionLimitsRouteImport.update({
  id: '/transaction-limits',
  path: '/transaction-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const TodaysBestOddsRoute = TodaysBestOddsRouteImport.update({
  id: '/todays-best-odds',
  path: '/todays-best-odds',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisRoute = TennisRouteImport.update({
  id: '/tennis',
  path: '/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramChannelRoute = TelegramChannelRouteImport.update({
  id: '/telegram-channel',
  path: '/telegram-channel',
  getParentRoute: () => rootRouteImport,
} as any)
const T20WorldCupBettingRoute = T20WorldCupBettingRouteImport.update({
  id: '/t20-world-cup-betting',
  path: '/t20-world-cup-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIdRoute = SportsIdRouteImport.update({
  id: '/sports-id',
  path: '/sports-id',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsBettingRoute = SportsBettingRouteImport.update({
  id: '/sports-betting',
  path: '/sports-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralCodeRoute = ReferralCodeRouteImport.update({
  id: '/referral-code',
  path: '/referral-code',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineBettingRoute = OnlineBettingRouteImport.update({
  id: '/online-betting',
  path: '/online-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIssuesRoute = LoginIssuesRouteImport.update({
  id: '/login-issues',
  path: '/login-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycPolicyRoute = KycPolicyRouteImport.update({
  id: '/kyc-policy',
  path: '/kyc-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KabaddiRoute = KabaddiRouteImport.update({
  id: '/kabaddi',
  path: '/kabaddi',
  getParentRoute: () => rootRouteImport,
} as any)
const IsCricbet99SafeRoute = IsCricbet99SafeRouteImport.update({
  id: '/is-cricbet99-safe',
  path: '/is-cricbet99-safe',
  getParentRoute: () => rootRouteImport,
} as any)
const IsCricbet99RealRoute = IsCricbet99RealRouteImport.update({
  id: '/is-cricbet99-real',
  path: '/is-cricbet99-real',
  getParentRoute: () => rootRouteImport,
} as any)
const IsCricbet99LegalRoute = IsCricbet99LegalRouteImport.update({
  id: '/is-cricbet99-legal',
  path: '/is-cricbet99-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IplBettingRoute = IplBettingRouteImport.update({
  id: '/ipl-betting',
  path: '/ipl-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const Ipl2026CalendarRoute = Ipl2026CalendarRouteImport.update({
  id: '/ipl-2026-calendar',
  path: '/ipl-2026-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndianCardGamesRoute = IndianCardGamesRouteImport.update({
  id: '/indian-card-games',
  path: '/indian-card-games',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToWithdrawRoute = HowToWithdrawRouteImport.update({
  id: '/how-to-withdraw',
  path: '/how-to-withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToDepositRoute = HowToDepositRouteImport.update({
  id: '/how-to-deposit',
  path: '/how-to-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HorseRacingRoute = HorseRacingRouteImport.update({
  id: '/horse-racing',
  path: '/horse-racing',
  getParentRoute: () => rootRouteImport,
} as any)
const HighOddsBettingStrategyRoute = HighOddsBettingStrategyRouteImport.update({
  id: '/high-odds-betting-strategy',
  path: '/high-odds-betting-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballRoute = FootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsRoute = EsportsRouteImport.update({
  id: '/esports',
  path: '/esports',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositIssuesRoute = DepositIssuesRouteImport.update({
  id: '/deposit-issues',
  path: '/deposit-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo-id',
  path: '/demo-id',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketRoute = CricketRouteImport.update({
  id: '/cricket',
  path: '/cricket',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsSkyexchange247Route =
  Cricbet99VsSkyexchange247RouteImport.update({
    id: '/cricbet99-vs-skyexchange247',
    path: '/cricbet99-vs-skyexchange247',
    getParentRoute: () => rootRouteImport,
  } as any)
const Cricbet99VsReddybookRoute = Cricbet99VsReddybookRouteImport.update({
  id: '/cricbet99-vs-reddybook',
  path: '/cricbet99-vs-reddybook',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsMahavirBookRoute = Cricbet99VsMahavirBookRouteImport.update({
  id: '/cricbet99-vs-mahavir-book',
  path: '/cricbet99-vs-mahavir-book',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsLotus365Route = Cricbet99VsLotus365RouteImport.update({
  id: '/cricbet99-vs-lotus365',
  path: '/cricbet99-vs-lotus365',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsLaser247Route = Cricbet99VsLaser247RouteImport.update({
  id: '/cricbet99-vs-laser247',
  path: '/cricbet99-vs-laser247',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsGold365Route = Cricbet99VsGold365RouteImport.update({
  id: '/cricbet99-vs-gold365',
  path: '/cricbet99-vs-gold365',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsFairdealRoute = Cricbet99VsFairdealRouteImport.update({
  id: '/cricbet99-vs-fairdeal',
  path: '/cricbet99-vs-fairdeal',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99VsDiamondExchangeRoute =
  Cricbet99VsDiamondExchangeRouteImport.update({
    id: '/cricbet99-vs-diamond-exchange',
    path: '/cricbet99-vs-diamond-exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const Cricbet99Vs11xplayRoute = Cricbet99Vs11xplayRouteImport.update({
  id: '/cricbet99-vs-11xplay',
  path: '/cricbet99-vs-11xplay',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99IdRoute = Cricbet99IdRouteImport.update({
  id: '/cricbet99-id',
  path: '/cricbet99-id',
  getParentRoute: () => rootRouteImport,
} as any)
const Cricbet99AppRoute = Cricbet99AppRouteImport.update({
  id: '/cricbet99-app',
  path: '/cricbet99-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsTrophyBettingRoute = ChampionsTrophyBettingRouteImport.update({
  id: '/champions-trophy-betting',
  path: '/champions-trophy-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusIssuesRoute = BonusIssuesRouteImport.update({
  id: '/bonus-issues',
  path: '/bonus-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRoute = BonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const BigWinStoriesRoute = BigWinStoriesRouteImport.update({
  id: '/big-win-stories',
  path: '/big-win-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingGuidesRoute = BettingGuidesRouteImport.update({
  id: '/betting-guides',
  path: '/betting-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAgentRoute = BecomeAgentRouteImport.update({
  id: '/become-agent',
  path: '/become-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const AllLinksRoute = AllLinksRouteImport.update({
  id: '/all-links',
  path: '/all-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBlockedRoute = AccountBlockedRouteImport.update({
  id: '/account-blocked',
  path: '/account-blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesSlugRoute = MatchesSlugRouteImport.update({
  id: '/matches/$slug',
  path: '/matches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesTossMarket10MinuteProfitRoute =
  CaseStudiesTossMarket10MinuteProfitRouteImport.update({
    id: '/toss-market-10-minute-profit',
    path: '/toss-market-10-minute-profit',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesSmallBudgetBettingStrategyRoute =
  CaseStudiesSmallBudgetBettingStrategyRouteImport.update({
    id: '/small-budget-betting-strategy',
    path: '/small-budget-betting-strategy',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesLiveBetting3xReturnsRoute =
  CaseStudiesLiveBetting3xReturnsRouteImport.update({
    id: '/live-betting-3x-returns',
    path: '/live-betting-3x-returns',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesIpl5000To25000ProfitRoute =
  CaseStudiesIpl5000To25000ProfitRouteImport.update({
    id: '/ipl-5000-to-25000-profit',
    path: '/ipl-5000-to-25000-profit',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingGuidesHowToSetBettingLimitsRoute =
  BettingGuidesHowToSetBettingLimitsRouteImport.update({
    id: '/how-to-set-betting-limits',
    path: '/how-to-set-betting-limits',
    getParentRoute: () => BettingGuidesRoute,
  } as any)
const BettingGuidesHowToPlaceALiveBetRoute =
  BettingGuidesHowToPlaceALiveBetRouteImport.update({
    id: '/how-to-place-a-live-bet',
    path: '/how-to-place-a-live-bet',
    getParentRoute: () => BettingGuidesRoute,
  } as any)
const BettingGuidesHowToPlaceACricketBetRoute =
  BettingGuidesHowToPlaceACricketBetRouteImport.update({
    id: '/how-to-place-a-cricket-bet',
    path: '/how-to-place-a-cricket-bet',
    getParentRoute: () => BettingGuidesRoute,
  } as any)
const BettingGuidesHowToBetOnTossMarketRoute =
  BettingGuidesHowToBetOnTossMarketRouteImport.update({
    id: '/how-to-bet-on-toss-market',
    path: '/how-to-bet-on-toss-market',
    getParentRoute: () => BettingGuidesRoute,
  } as any)
const BettingGuidesHowToBetOnSessionBettingRoute =
  BettingGuidesHowToBetOnSessionBettingRouteImport.update({
    id: '/how-to-bet-on-session-betting',
    path: '/how-to-bet-on-session-betting',
    getParentRoute: () => BettingGuidesRoute,
  } as any)
const BettingGuidesHowBookmakersMakeMoneyRoute =
  BettingGuidesHowBookmakersMakeMoneyRouteImport.update({
    id: '/how-bookmakers-make-money',
    path: '/how-bookmakers-make-money',
    getParentRoute: () => BettingGuidesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-blocked': typeof AccountBlockedRoute
  '/all-links': typeof AllLinksRoute
  '/basketball': typeof BasketballRoute
  '/become-agent': typeof BecomeAgentRoute
  '/betting-guides': typeof BettingGuidesRouteWithChildren
  '/big-win-stories': typeof BigWinStoriesRoute
  '/bonus': typeof BonusRoute
  '/bonus-issues': typeof BonusIssuesRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/casino': typeof CasinoRoute
  '/champions-trophy-betting': typeof ChampionsTrophyBettingRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cricbet99-app': typeof Cricbet99AppRoute
  '/cricbet99-id': typeof Cricbet99IdRoute
  '/cricbet99-vs-11xplay': typeof Cricbet99Vs11xplayRoute
  '/cricbet99-vs-diamond-exchange': typeof Cricbet99VsDiamondExchangeRoute
  '/cricbet99-vs-fairdeal': typeof Cricbet99VsFairdealRoute
  '/cricbet99-vs-gold365': typeof Cricbet99VsGold365Route
  '/cricbet99-vs-laser247': typeof Cricbet99VsLaser247Route
  '/cricbet99-vs-lotus365': typeof Cricbet99VsLotus365Route
  '/cricbet99-vs-mahavir-book': typeof Cricbet99VsMahavirBookRoute
  '/cricbet99-vs-reddybook': typeof Cricbet99VsReddybookRoute
  '/cricbet99-vs-skyexchange247': typeof Cricbet99VsSkyexchange247Route
  '/cricket': typeof CricketRoute
  '/demo-id': typeof DemoIdRoute
  '/deposit-issues': typeof DepositIssuesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/esports': typeof EsportsRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/football': typeof FootballRoute
  '/high-odds-betting-strategy': typeof HighOddsBettingStrategyRoute
  '/horse-racing': typeof HorseRacingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-to-deposit': typeof HowToDepositRoute
  '/how-to-withdraw': typeof HowToWithdrawRoute
  '/indian-card-games': typeof IndianCardGamesRoute
  '/ipl-2026-calendar': typeof Ipl2026CalendarRoute
  '/ipl-betting': typeof IplBettingRoute
  '/is-cricbet99-legal': typeof IsCricbet99LegalRoute
  '/is-cricbet99-real': typeof IsCricbet99RealRoute
  '/is-cricbet99-safe': typeof IsCricbet99SafeRoute
  '/kabaddi': typeof KabaddiRoute
  '/kyc-policy': typeof KycPolicyRoute
  '/login': typeof LoginRoute
  '/login-issues': typeof LoginIssuesRoute
  '/online-betting': typeof OnlineBettingRoute
  '/platforms': typeof PlatformsRoute
  '/policies': typeof PoliciesRoute
  '/predictions': typeof PredictionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/referral-code': typeof ReferralCodeRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/schedule': typeof ScheduleRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/sports-id': typeof SportsIdRoute
  '/support': typeof SupportRoute
  '/t20-world-cup-betting': typeof T20WorldCupBettingRoute
  '/telegram-channel': typeof TelegramChannelRoute
  '/tennis': typeof TennisRoute
  '/terms': typeof TermsRoute
  '/todays-best-odds': typeof TodaysBestOddsRoute
  '/transaction-limits': typeof TransactionLimitsRoute
  '/trusted-betting-agent': typeof TrustedBettingAgentRoute
  '/trusted-betting-id-provider': typeof TrustedBettingIdProviderRoute
  '/what-is-cricbet99': typeof WhatIsCricbet99Route
  '/whatsapp-number': typeof WhatsappNumberRoute
  '/whatsapp-support': typeof WhatsappSupportRoute
  '/why-choose-cricbet99': typeof WhyChooseCricbet99Route
  '/withdrawal-delay': typeof WithdrawalDelayRoute
  '/wpl-2026-betting': typeof Wpl2026BettingRoute
  '/betting-guides/how-bookmakers-make-money': typeof BettingGuidesHowBookmakersMakeMoneyRoute
  '/betting-guides/how-to-bet-on-session-betting': typeof BettingGuidesHowToBetOnSessionBettingRoute
  '/betting-guides/how-to-bet-on-toss-market': typeof BettingGuidesHowToBetOnTossMarketRoute
  '/betting-guides/how-to-place-a-cricket-bet': typeof BettingGuidesHowToPlaceACricketBetRoute
  '/betting-guides/how-to-place-a-live-bet': typeof BettingGuidesHowToPlaceALiveBetRoute
  '/betting-guides/how-to-set-betting-limits': typeof BettingGuidesHowToSetBettingLimitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/ipl-5000-to-25000-profit': typeof CaseStudiesIpl5000To25000ProfitRoute
  '/case-studies/live-betting-3x-returns': typeof CaseStudiesLiveBetting3xReturnsRoute
  '/case-studies/small-budget-betting-strategy': typeof CaseStudiesSmallBudgetBettingStrategyRoute
  '/case-studies/toss-market-10-minute-profit': typeof CaseStudiesTossMarket10MinuteProfitRoute
  '/matches/$slug': typeof MatchesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-blocked': typeof AccountBlockedRoute
  '/all-links': typeof AllLinksRoute
  '/basketball': typeof BasketballRoute
  '/become-agent': typeof BecomeAgentRoute
  '/betting-guides': typeof BettingGuidesRouteWithChildren
  '/big-win-stories': typeof BigWinStoriesRoute
  '/bonus': typeof BonusRoute
  '/bonus-issues': typeof BonusIssuesRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/casino': typeof CasinoRoute
  '/champions-trophy-betting': typeof ChampionsTrophyBettingRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cricbet99-app': typeof Cricbet99AppRoute
  '/cricbet99-id': typeof Cricbet99IdRoute
  '/cricbet99-vs-11xplay': typeof Cricbet99Vs11xplayRoute
  '/cricbet99-vs-diamond-exchange': typeof Cricbet99VsDiamondExchangeRoute
  '/cricbet99-vs-fairdeal': typeof Cricbet99VsFairdealRoute
  '/cricbet99-vs-gold365': typeof Cricbet99VsGold365Route
  '/cricbet99-vs-laser247': typeof Cricbet99VsLaser247Route
  '/cricbet99-vs-lotus365': typeof Cricbet99VsLotus365Route
  '/cricbet99-vs-mahavir-book': typeof Cricbet99VsMahavirBookRoute
  '/cricbet99-vs-reddybook': typeof Cricbet99VsReddybookRoute
  '/cricbet99-vs-skyexchange247': typeof Cricbet99VsSkyexchange247Route
  '/cricket': typeof CricketRoute
  '/demo-id': typeof DemoIdRoute
  '/deposit-issues': typeof DepositIssuesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/esports': typeof EsportsRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/football': typeof FootballRoute
  '/high-odds-betting-strategy': typeof HighOddsBettingStrategyRoute
  '/horse-racing': typeof HorseRacingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-to-deposit': typeof HowToDepositRoute
  '/how-to-withdraw': typeof HowToWithdrawRoute
  '/indian-card-games': typeof IndianCardGamesRoute
  '/ipl-2026-calendar': typeof Ipl2026CalendarRoute
  '/ipl-betting': typeof IplBettingRoute
  '/is-cricbet99-legal': typeof IsCricbet99LegalRoute
  '/is-cricbet99-real': typeof IsCricbet99RealRoute
  '/is-cricbet99-safe': typeof IsCricbet99SafeRoute
  '/kabaddi': typeof KabaddiRoute
  '/kyc-policy': typeof KycPolicyRoute
  '/login': typeof LoginRoute
  '/login-issues': typeof LoginIssuesRoute
  '/online-betting': typeof OnlineBettingRoute
  '/platforms': typeof PlatformsRoute
  '/policies': typeof PoliciesRoute
  '/predictions': typeof PredictionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/referral-code': typeof ReferralCodeRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/schedule': typeof ScheduleRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/sports-id': typeof SportsIdRoute
  '/support': typeof SupportRoute
  '/t20-world-cup-betting': typeof T20WorldCupBettingRoute
  '/telegram-channel': typeof TelegramChannelRoute
  '/tennis': typeof TennisRoute
  '/terms': typeof TermsRoute
  '/todays-best-odds': typeof TodaysBestOddsRoute
  '/transaction-limits': typeof TransactionLimitsRoute
  '/trusted-betting-agent': typeof TrustedBettingAgentRoute
  '/trusted-betting-id-provider': typeof TrustedBettingIdProviderRoute
  '/what-is-cricbet99': typeof WhatIsCricbet99Route
  '/whatsapp-number': typeof WhatsappNumberRoute
  '/whatsapp-support': typeof WhatsappSupportRoute
  '/why-choose-cricbet99': typeof WhyChooseCricbet99Route
  '/withdrawal-delay': typeof WithdrawalDelayRoute
  '/wpl-2026-betting': typeof Wpl2026BettingRoute
  '/betting-guides/how-bookmakers-make-money': typeof BettingGuidesHowBookmakersMakeMoneyRoute
  '/betting-guides/how-to-bet-on-session-betting': typeof BettingGuidesHowToBetOnSessionBettingRoute
  '/betting-guides/how-to-bet-on-toss-market': typeof BettingGuidesHowToBetOnTossMarketRoute
  '/betting-guides/how-to-place-a-cricket-bet': typeof BettingGuidesHowToPlaceACricketBetRoute
  '/betting-guides/how-to-place-a-live-bet': typeof BettingGuidesHowToPlaceALiveBetRoute
  '/betting-guides/how-to-set-betting-limits': typeof BettingGuidesHowToSetBettingLimitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/ipl-5000-to-25000-profit': typeof CaseStudiesIpl5000To25000ProfitRoute
  '/case-studies/live-betting-3x-returns': typeof CaseStudiesLiveBetting3xReturnsRoute
  '/case-studies/small-budget-betting-strategy': typeof CaseStudiesSmallBudgetBettingStrategyRoute
  '/case-studies/toss-market-10-minute-profit': typeof CaseStudiesTossMarket10MinuteProfitRoute
  '/matches/$slug': typeof MatchesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/matches': typeof MatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-blocked': typeof AccountBlockedRoute
  '/all-links': typeof AllLinksRoute
  '/basketball': typeof BasketballRoute
  '/become-agent': typeof BecomeAgentRoute
  '/betting-guides': typeof BettingGuidesRouteWithChildren
  '/big-win-stories': typeof BigWinStoriesRoute
  '/bonus': typeof BonusRoute
  '/bonus-issues': typeof BonusIssuesRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/casino': typeof CasinoRoute
  '/champions-trophy-betting': typeof ChampionsTrophyBettingRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cricbet99-app': typeof Cricbet99AppRoute
  '/cricbet99-id': typeof Cricbet99IdRoute
  '/cricbet99-vs-11xplay': typeof Cricbet99Vs11xplayRoute
  '/cricbet99-vs-diamond-exchange': typeof Cricbet99VsDiamondExchangeRoute
  '/cricbet99-vs-fairdeal': typeof Cricbet99VsFairdealRoute
  '/cricbet99-vs-gold365': typeof Cricbet99VsGold365Route
  '/cricbet99-vs-laser247': typeof Cricbet99VsLaser247Route
  '/cricbet99-vs-lotus365': typeof Cricbet99VsLotus365Route
  '/cricbet99-vs-mahavir-book': typeof Cricbet99VsMahavirBookRoute
  '/cricbet99-vs-reddybook': typeof Cricbet99VsReddybookRoute
  '/cricbet99-vs-skyexchange247': typeof Cricbet99VsSkyexchange247Route
  '/cricket': typeof CricketRoute
  '/demo-id': typeof DemoIdRoute
  '/deposit-issues': typeof DepositIssuesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/esports': typeof EsportsRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/football': typeof FootballRoute
  '/high-odds-betting-strategy': typeof HighOddsBettingStrategyRoute
  '/horse-racing': typeof HorseRacingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-to-deposit': typeof HowToDepositRoute
  '/how-to-withdraw': typeof HowToWithdrawRoute
  '/indian-card-games': typeof IndianCardGamesRoute
  '/ipl-2026-calendar': typeof Ipl2026CalendarRoute
  '/ipl-betting': typeof IplBettingRoute
  '/is-cricbet99-legal': typeof IsCricbet99LegalRoute
  '/is-cricbet99-real': typeof IsCricbet99RealRoute
  '/is-cricbet99-safe': typeof IsCricbet99SafeRoute
  '/kabaddi': typeof KabaddiRoute
  '/kyc-policy': typeof KycPolicyRoute
  '/login': typeof LoginRoute
  '/login-issues': typeof LoginIssuesRoute
  '/online-betting': typeof OnlineBettingRoute
  '/platforms': typeof PlatformsRoute
  '/policies': typeof PoliciesRoute
  '/predictions': typeof PredictionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/referral-code': typeof ReferralCodeRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/schedule': typeof ScheduleRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/sports-id': typeof SportsIdRoute
  '/support': typeof SupportRoute
  '/t20-world-cup-betting': typeof T20WorldCupBettingRoute
  '/telegram-channel': typeof TelegramChannelRoute
  '/tennis': typeof TennisRoute
  '/terms': typeof TermsRoute
  '/todays-best-odds': typeof TodaysBestOddsRoute
  '/transaction-limits': typeof TransactionLimitsRoute
  '/trusted-betting-agent': typeof TrustedBettingAgentRoute
  '/trusted-betting-id-provider': typeof TrustedBettingIdProviderRoute
  '/what-is-cricbet99': typeof WhatIsCricbet99Route
  '/whatsapp-number': typeof WhatsappNumberRoute
  '/whatsapp-support': typeof WhatsappSupportRoute
  '/why-choose-cricbet99': typeof WhyChooseCricbet99Route
  '/withdrawal-delay': typeof WithdrawalDelayRoute
  '/wpl-2026-betting': typeof Wpl2026BettingRoute
  '/betting-guides/how-bookmakers-make-money': typeof BettingGuidesHowBookmakersMakeMoneyRoute
  '/betting-guides/how-to-bet-on-session-betting': typeof BettingGuidesHowToBetOnSessionBettingRoute
  '/betting-guides/how-to-bet-on-toss-market': typeof BettingGuidesHowToBetOnTossMarketRoute
  '/betting-guides/how-to-place-a-cricket-bet': typeof BettingGuidesHowToPlaceACricketBetRoute
  '/betting-guides/how-to-place-a-live-bet': typeof BettingGuidesHowToPlaceALiveBetRoute
  '/betting-guides/how-to-set-betting-limits': typeof BettingGuidesHowToSetBettingLimitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/ipl-5000-to-25000-profit': typeof CaseStudiesIpl5000To25000ProfitRoute
  '/case-studies/live-betting-3x-returns': typeof CaseStudiesLiveBetting3xReturnsRoute
  '/case-studies/small-budget-betting-strategy': typeof CaseStudiesSmallBudgetBettingStrategyRoute
  '/case-studies/toss-market-10-minute-profit': typeof CaseStudiesTossMarket10MinuteProfitRoute
  '/matches/$slug': typeof MatchesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account-blocked'
    | '/all-links'
    | '/basketball'
    | '/become-agent'
    | '/betting-guides'
    | '/big-win-stories'
    | '/bonus'
    | '/bonus-issues'
    | '/case-studies'
    | '/casino'
    | '/champions-trophy-betting'
    | '/community-guidelines'
    | '/contact'
    | '/cricbet99-app'
    | '/cricbet99-id'
    | '/cricbet99-vs-11xplay'
    | '/cricbet99-vs-diamond-exchange'
    | '/cricbet99-vs-fairdeal'
    | '/cricbet99-vs-gold365'
    | '/cricbet99-vs-laser247'
    | '/cricbet99-vs-lotus365'
    | '/cricbet99-vs-mahavir-book'
    | '/cricbet99-vs-reddybook'
    | '/cricbet99-vs-skyexchange247'
    | '/cricket'
    | '/demo-id'
    | '/deposit-issues'
    | '/disclaimer'
    | '/esports'
    | '/exchange'
    | '/faq'
    | '/football'
    | '/high-odds-betting-strategy'
    | '/horse-racing'
    | '/how-it-works'
    | '/how-to-deposit'
    | '/how-to-withdraw'
    | '/indian-card-games'
    | '/ipl-2026-calendar'
    | '/ipl-betting'
    | '/is-cricbet99-legal'
    | '/is-cricbet99-real'
    | '/is-cricbet99-safe'
    | '/kabaddi'
    | '/kyc-policy'
    | '/login'
    | '/login-issues'
    | '/online-betting'
    | '/platforms'
    | '/policies'
    | '/predictions'
    | '/privacy-policy'
    | '/referral-code'
    | '/refund-policy'
    | '/register'
    | '/responsible-gaming'
    | '/reviews'
    | '/rules'
    | '/schedule'
    | '/security'
    | '/services'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/sports-id'
    | '/support'
    | '/t20-world-cup-betting'
    | '/telegram-channel'
    | '/tennis'
    | '/terms'
    | '/todays-best-odds'
    | '/transaction-limits'
    | '/trusted-betting-agent'
    | '/trusted-betting-id-provider'
    | '/what-is-cricbet99'
    | '/whatsapp-number'
    | '/whatsapp-support'
    | '/why-choose-cricbet99'
    | '/withdrawal-delay'
    | '/wpl-2026-betting'
    | '/betting-guides/how-bookmakers-make-money'
    | '/betting-guides/how-to-bet-on-session-betting'
    | '/betting-guides/how-to-bet-on-toss-market'
    | '/betting-guides/how-to-place-a-cricket-bet'
    | '/betting-guides/how-to-place-a-live-bet'
    | '/betting-guides/how-to-set-betting-limits'
    | '/blog/$slug'
    | '/case-studies/ipl-5000-to-25000-profit'
    | '/case-studies/live-betting-3x-returns'
    | '/case-studies/small-budget-betting-strategy'
    | '/case-studies/toss-market-10-minute-profit'
    | '/matches/$slug'
    | '/blog/'
    | '/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account-blocked'
    | '/all-links'
    | '/basketball'
    | '/become-agent'
    | '/betting-guides'
    | '/big-win-stories'
    | '/bonus'
    | '/bonus-issues'
    | '/case-studies'
    | '/casino'
    | '/champions-trophy-betting'
    | '/community-guidelines'
    | '/contact'
    | '/cricbet99-app'
    | '/cricbet99-id'
    | '/cricbet99-vs-11xplay'
    | '/cricbet99-vs-diamond-exchange'
    | '/cricbet99-vs-fairdeal'
    | '/cricbet99-vs-gold365'
    | '/cricbet99-vs-laser247'
    | '/cricbet99-vs-lotus365'
    | '/cricbet99-vs-mahavir-book'
    | '/cricbet99-vs-reddybook'
    | '/cricbet99-vs-skyexchange247'
    | '/cricket'
    | '/demo-id'
    | '/deposit-issues'
    | '/disclaimer'
    | '/esports'
    | '/exchange'
    | '/faq'
    | '/football'
    | '/high-odds-betting-strategy'
    | '/horse-racing'
    | '/how-it-works'
    | '/how-to-deposit'
    | '/how-to-withdraw'
    | '/indian-card-games'
    | '/ipl-2026-calendar'
    | '/ipl-betting'
    | '/is-cricbet99-legal'
    | '/is-cricbet99-real'
    | '/is-cricbet99-safe'
    | '/kabaddi'
    | '/kyc-policy'
    | '/login'
    | '/login-issues'
    | '/online-betting'
    | '/platforms'
    | '/policies'
    | '/predictions'
    | '/privacy-policy'
    | '/referral-code'
    | '/refund-policy'
    | '/register'
    | '/responsible-gaming'
    | '/reviews'
    | '/rules'
    | '/schedule'
    | '/security'
    | '/services'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/sports-id'
    | '/support'
    | '/t20-world-cup-betting'
    | '/telegram-channel'
    | '/tennis'
    | '/terms'
    | '/todays-best-odds'
    | '/transaction-limits'
    | '/trusted-betting-agent'
    | '/trusted-betting-id-provider'
    | '/what-is-cricbet99'
    | '/whatsapp-number'
    | '/whatsapp-support'
    | '/why-choose-cricbet99'
    | '/withdrawal-delay'
    | '/wpl-2026-betting'
    | '/betting-guides/how-bookmakers-make-money'
    | '/betting-guides/how-to-bet-on-session-betting'
    | '/betting-guides/how-to-bet-on-toss-market'
    | '/betting-guides/how-to-place-a-cricket-bet'
    | '/betting-guides/how-to-place-a-live-bet'
    | '/betting-guides/how-to-set-betting-limits'
    | '/blog/$slug'
    | '/case-studies/ipl-5000-to-25000-profit'
    | '/case-studies/live-betting-3x-returns'
    | '/case-studies/small-budget-betting-strategy'
    | '/case-studies/toss-market-10-minute-profit'
    | '/matches/$slug'
    | '/blog'
    | '/matches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account-blocked'
    | '/all-links'
    | '/basketball'
    | '/become-agent'
    | '/betting-guides'
    | '/big-win-stories'
    | '/bonus'
    | '/bonus-issues'
    | '/case-studies'
    | '/casino'
    | '/champions-trophy-betting'
    | '/community-guidelines'
    | '/contact'
    | '/cricbet99-app'
    | '/cricbet99-id'
    | '/cricbet99-vs-11xplay'
    | '/cricbet99-vs-diamond-exchange'
    | '/cricbet99-vs-fairdeal'
    | '/cricbet99-vs-gold365'
    | '/cricbet99-vs-laser247'
    | '/cricbet99-vs-lotus365'
    | '/cricbet99-vs-mahavir-book'
    | '/cricbet99-vs-reddybook'
    | '/cricbet99-vs-skyexchange247'
    | '/cricket'
    | '/demo-id'
    | '/deposit-issues'
    | '/disclaimer'
    | '/esports'
    | '/exchange'
    | '/faq'
    | '/football'
    | '/high-odds-betting-strategy'
    | '/horse-racing'
    | '/how-it-works'
    | '/how-to-deposit'
    | '/how-to-withdraw'
    | '/indian-card-games'
    | '/ipl-2026-calendar'
    | '/ipl-betting'
    | '/is-cricbet99-legal'
    | '/is-cricbet99-real'
    | '/is-cricbet99-safe'
    | '/kabaddi'
    | '/kyc-policy'
    | '/login'
    | '/login-issues'
    | '/online-betting'
    | '/platforms'
    | '/policies'
    | '/predictions'
    | '/privacy-policy'
    | '/referral-code'
    | '/refund-policy'
    | '/register'
    | '/responsible-gaming'
    | '/reviews'
    | '/rules'
    | '/schedule'
    | '/security'
    | '/services'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/sports-id'
    | '/support'
    | '/t20-world-cup-betting'
    | '/telegram-channel'
    | '/tennis'
    | '/terms'
    | '/todays-best-odds'
    | '/transaction-limits'
    | '/trusted-betting-agent'
    | '/trusted-betting-id-provider'
    | '/what-is-cricbet99'
    | '/whatsapp-number'
    | '/whatsapp-support'
    | '/why-choose-cricbet99'
    | '/withdrawal-delay'
    | '/wpl-2026-betting'
    | '/betting-guides/how-bookmakers-make-money'
    | '/betting-guides/how-to-bet-on-session-betting'
    | '/betting-guides/how-to-bet-on-toss-market'
    | '/betting-guides/how-to-place-a-cricket-bet'
    | '/betting-guides/how-to-place-a-live-bet'
    | '/betting-guides/how-to-set-betting-limits'
    | '/blog/$slug'
    | '/case-studies/ipl-5000-to-25000-profit'
    | '/case-studies/live-betting-3x-returns'
    | '/case-studies/small-budget-betting-strategy'
    | '/case-studies/toss-market-10-minute-profit'
    | '/matches/$slug'
    | '/blog/'
    | '/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountBlockedRoute: typeof AccountBlockedRoute
  AllLinksRoute: typeof AllLinksRoute
  BasketballRoute: typeof BasketballRoute
  BecomeAgentRoute: typeof BecomeAgentRoute
  BettingGuidesRoute: typeof BettingGuidesRouteWithChildren
  BigWinStoriesRoute: typeof BigWinStoriesRoute
  BonusRoute: typeof BonusRoute
  BonusIssuesRoute: typeof BonusIssuesRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  CasinoRoute: typeof CasinoRoute
  ChampionsTrophyBettingRoute: typeof ChampionsTrophyBettingRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  Cricbet99AppRoute: typeof Cricbet99AppRoute
  Cricbet99IdRoute: typeof Cricbet99IdRoute
  Cricbet99Vs11xplayRoute: typeof Cricbet99Vs11xplayRoute
  Cricbet99VsDiamondExchangeRoute: typeof Cricbet99VsDiamondExchangeRoute
  Cricbet99VsFairdealRoute: typeof Cricbet99VsFairdealRoute
  Cricbet99VsGold365Route: typeof Cricbet99VsGold365Route
  Cricbet99VsLaser247Route: typeof Cricbet99VsLaser247Route
  Cricbet99VsLotus365Route: typeof Cricbet99VsLotus365Route
  Cricbet99VsMahavirBookRoute: typeof Cricbet99VsMahavirBookRoute
  Cricbet99VsReddybookRoute: typeof Cricbet99VsReddybookRoute
  Cricbet99VsSkyexchange247Route: typeof Cricbet99VsSkyexchange247Route
  CricketRoute: typeof CricketRoute
  DemoIdRoute: typeof DemoIdRoute
  DepositIssuesRoute: typeof DepositIssuesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EsportsRoute: typeof EsportsRoute
  ExchangeRoute: typeof ExchangeRoute
  FaqRoute: typeof FaqRoute
  FootballRoute: typeof FootballRoute
  HighOddsBettingStrategyRoute: typeof HighOddsBettingStrategyRoute
  HorseRacingRoute: typeof HorseRacingRoute
  HowItWorksRoute: typeof HowItWorksRoute
  HowToDepositRoute: typeof HowToDepositRoute
  HowToWithdrawRoute: typeof HowToWithdrawRoute
  IndianCardGamesRoute: typeof IndianCardGamesRoute
  Ipl2026CalendarRoute: typeof Ipl2026CalendarRoute
  IplBettingRoute: typeof IplBettingRoute
  IsCricbet99LegalRoute: typeof IsCricbet99LegalRoute
  IsCricbet99RealRoute: typeof IsCricbet99RealRoute
  IsCricbet99SafeRoute: typeof IsCricbet99SafeRoute
  KabaddiRoute: typeof KabaddiRoute
  KycPolicyRoute: typeof KycPolicyRoute
  LoginRoute: typeof LoginRoute
  LoginIssuesRoute: typeof LoginIssuesRoute
  OnlineBettingRoute: typeof OnlineBettingRoute
  PlatformsRoute: typeof PlatformsRoute
  PoliciesRoute: typeof PoliciesRoute
  PredictionsRoute: typeof PredictionsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReferralCodeRoute: typeof ReferralCodeRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  ReviewsRoute: typeof ReviewsRoute
  RulesRoute: typeof RulesRoute
  ScheduleRoute: typeof ScheduleRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsBettingRoute: typeof SportsBettingRoute
  SportsIdRoute: typeof SportsIdRoute
  SupportRoute: typeof SupportRoute
  T20WorldCupBettingRoute: typeof T20WorldCupBettingRoute
  TelegramChannelRoute: typeof TelegramChannelRoute
  TennisRoute: typeof TennisRoute
  TermsRoute: typeof TermsRoute
  TodaysBestOddsRoute: typeof TodaysBestOddsRoute
  TransactionLimitsRoute: typeof TransactionLimitsRoute
  TrustedBettingAgentRoute: typeof TrustedBettingAgentRoute
  TrustedBettingIdProviderRoute: typeof TrustedBettingIdProviderRoute
  WhatIsCricbet99Route: typeof WhatIsCricbet99Route
  WhatsappNumberRoute: typeof WhatsappNumberRoute
  WhatsappSupportRoute: typeof WhatsappSupportRoute
  WhyChooseCricbet99Route: typeof WhyChooseCricbet99Route
  WithdrawalDelayRoute: typeof WithdrawalDelayRoute
  Wpl2026BettingRoute: typeof Wpl2026BettingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MatchesSlugRoute: typeof MatchesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wpl-2026-betting': {
      id: '/wpl-2026-betting'
      path: '/wpl-2026-betting'
      fullPath: '/wpl-2026-betting'
      preLoaderRoute: typeof Wpl2026BettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal-delay': {
      id: '/withdrawal-delay'
      path: '/withdrawal-delay'
      fullPath: '/withdrawal-delay'
      preLoaderRoute: typeof WithdrawalDelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-cricbet99': {
      id: '/why-choose-cricbet99'
      path: '/why-choose-cricbet99'
      fullPath: '/why-choose-cricbet99'
      preLoaderRoute: typeof WhyChooseCricbet99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-support': {
      id: '/whatsapp-support'
      path: '/whatsapp-support'
      fullPath: '/whatsapp-support'
      preLoaderRoute: typeof WhatsappSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-number': {
      id: '/whatsapp-number'
      path: '/whatsapp-number'
      fullPath: '/whatsapp-number'
      preLoaderRoute: typeof WhatsappNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-cricbet99': {
      id: '/what-is-cricbet99'
      path: '/what-is-cricbet99'
      fullPath: '/what-is-cricbet99'
      preLoaderRoute: typeof WhatIsCricbet99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted-betting-id-provider': {
      id: '/trusted-betting-id-provider'
      path: '/trusted-betting-id-provider'
      fullPath: '/trusted-betting-id-provider'
      preLoaderRoute: typeof TrustedBettingIdProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted-betting-agent': {
      id: '/trusted-betting-agent'
      path: '/trusted-betting-agent'
      fullPath: '/trusted-betting-agent'
      preLoaderRoute: typeof TrustedBettingAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction-limits': {
      id: '/transaction-limits'
      path: '/transaction-limits'
      fullPath: '/transaction-limits'
      preLoaderRoute: typeof TransactionLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todays-best-odds': {
      id: '/todays-best-odds'
      path: '/todays-best-odds'
      fullPath: '/todays-best-odds'
      preLoaderRoute: typeof TodaysBestOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis': {
      id: '/tennis'
      path: '/tennis'
      fullPath: '/tennis'
      preLoaderRoute: typeof TennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-channel': {
      id: '/telegram-channel'
      path: '/telegram-channel'
      fullPath: '/telegram-channel'
      preLoaderRoute: typeof TelegramChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t20-world-cup-betting': {
      id: '/t20-world-cup-betting'
      path: '/t20-world-cup-betting'
      fullPath: '/t20-world-cup-betting'
      preLoaderRoute: typeof T20WorldCupBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-id': {
      id: '/sports-id'
      path: '/sports-id'
      fullPath: '/sports-id'
      preLoaderRoute: typeof SportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-betting': {
      id: '/sports-betting'
      path: '/sports-betting'
      fullPath: '/sports-betting'
      preLoaderRoute: typeof SportsBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral-code': {
      id: '/referral-code'
      path: '/referral-code'
      fullPath: '/referral-code'
      preLoaderRoute: typeof ReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-betting': {
      id: '/online-betting'
      path: '/online-betting'
      fullPath: '/online-betting'
      preLoaderRoute: typeof OnlineBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-issues': {
      id: '/login-issues'
      path: '/login-issues'
      fullPath: '/login-issues'
      preLoaderRoute: typeof LoginIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc-policy': {
      id: '/kyc-policy'
      path: '/kyc-policy'
      fullPath: '/kyc-policy'
      preLoaderRoute: typeof KycPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabaddi': {
      id: '/kabaddi'
      path: '/kabaddi'
      fullPath: '/kabaddi'
      preLoaderRoute: typeof KabaddiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-cricbet99-safe': {
      id: '/is-cricbet99-safe'
      path: '/is-cricbet99-safe'
      fullPath: '/is-cricbet99-safe'
      preLoaderRoute: typeof IsCricbet99SafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-cricbet99-real': {
      id: '/is-cricbet99-real'
      path: '/is-cricbet99-real'
      fullPath: '/is-cricbet99-real'
      preLoaderRoute: typeof IsCricbet99RealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-cricbet99-legal': {
      id: '/is-cricbet99-legal'
      path: '/is-cricbet99-legal'
      fullPath: '/is-cricbet99-legal'
      preLoaderRoute: typeof IsCricbet99LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl-betting': {
      id: '/ipl-betting'
      path: '/ipl-betting'
      fullPath: '/ipl-betting'
      preLoaderRoute: typeof IplBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl-2026-calendar': {
      id: '/ipl-2026-calendar'
      path: '/ipl-2026-calendar'
      fullPath: '/ipl-2026-calendar'
      preLoaderRoute: typeof Ipl2026CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-card-games': {
      id: '/indian-card-games'
      path: '/indian-card-games'
      fullPath: '/indian-card-games'
      preLoaderRoute: typeof IndianCardGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-withdraw': {
      id: '/how-to-withdraw'
      path: '/how-to-withdraw'
      fullPath: '/how-to-withdraw'
      preLoaderRoute: typeof HowToWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-deposit': {
      id: '/how-to-deposit'
      path: '/how-to-deposit'
      fullPath: '/how-to-deposit'
      preLoaderRoute: typeof HowToDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horse-racing': {
      id: '/horse-racing'
      path: '/horse-racing'
      fullPath: '/horse-racing'
      preLoaderRoute: typeof HorseRacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-odds-betting-strategy': {
      id: '/high-odds-betting-strategy'
      path: '/high-odds-betting-strategy'
      fullPath: '/high-odds-betting-strategy'
      preLoaderRoute: typeof HighOddsBettingStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football': {
      id: '/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof FootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports': {
      id: '/esports'
      path: '/esports'
      fullPath: '/esports'
      preLoaderRoute: typeof EsportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-issues': {
      id: '/deposit-issues'
      path: '/deposit-issues'
      fullPath: '/deposit-issues'
      preLoaderRoute: typeof DepositIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-id': {
      id: '/demo-id'
      path: '/demo-id'
      fullPath: '/demo-id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket': {
      id: '/cricket'
      path: '/cricket'
      fullPath: '/cricket'
      preLoaderRoute: typeof CricketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-skyexchange247': {
      id: '/cricbet99-vs-skyexchange247'
      path: '/cricbet99-vs-skyexchange247'
      fullPath: '/cricbet99-vs-skyexchange247'
      preLoaderRoute: typeof Cricbet99VsSkyexchange247RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-reddybook': {
      id: '/cricbet99-vs-reddybook'
      path: '/cricbet99-vs-reddybook'
      fullPath: '/cricbet99-vs-reddybook'
      preLoaderRoute: typeof Cricbet99VsReddybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-mahavir-book': {
      id: '/cricbet99-vs-mahavir-book'
      path: '/cricbet99-vs-mahavir-book'
      fullPath: '/cricbet99-vs-mahavir-book'
      preLoaderRoute: typeof Cricbet99VsMahavirBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-lotus365': {
      id: '/cricbet99-vs-lotus365'
      path: '/cricbet99-vs-lotus365'
      fullPath: '/cricbet99-vs-lotus365'
      preLoaderRoute: typeof Cricbet99VsLotus365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-laser247': {
      id: '/cricbet99-vs-laser247'
      path: '/cricbet99-vs-laser247'
      fullPath: '/cricbet99-vs-laser247'
      preLoaderRoute: typeof Cricbet99VsLaser247RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-gold365': {
      id: '/cricbet99-vs-gold365'
      path: '/cricbet99-vs-gold365'
      fullPath: '/cricbet99-vs-gold365'
      preLoaderRoute: typeof Cricbet99VsGold365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-fairdeal': {
      id: '/cricbet99-vs-fairdeal'
      path: '/cricbet99-vs-fairdeal'
      fullPath: '/cricbet99-vs-fairdeal'
      preLoaderRoute: typeof Cricbet99VsFairdealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-diamond-exchange': {
      id: '/cricbet99-vs-diamond-exchange'
      path: '/cricbet99-vs-diamond-exchange'
      fullPath: '/cricbet99-vs-diamond-exchange'
      preLoaderRoute: typeof Cricbet99VsDiamondExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-vs-11xplay': {
      id: '/cricbet99-vs-11xplay'
      path: '/cricbet99-vs-11xplay'
      fullPath: '/cricbet99-vs-11xplay'
      preLoaderRoute: typeof Cricbet99Vs11xplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-id': {
      id: '/cricbet99-id'
      path: '/cricbet99-id'
      fullPath: '/cricbet99-id'
      preLoaderRoute: typeof Cricbet99IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricbet99-app': {
      id: '/cricbet99-app'
      path: '/cricbet99-app'
      fullPath: '/cricbet99-app'
      preLoaderRoute: typeof Cricbet99AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions-trophy-betting': {
      id: '/champions-trophy-betting'
      path: '/champions-trophy-betting'
      fullPath: '/champions-trophy-betting'
      preLoaderRoute: typeof ChampionsTrophyBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-issues': {
      id: '/bonus-issues'
      path: '/bonus-issues'
      fullPath: '/bonus-issues'
      preLoaderRoute: typeof BonusIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/big-win-stories': {
      id: '/big-win-stories'
      path: '/big-win-stories'
      fullPath: '/big-win-stories'
      preLoaderRoute: typeof BigWinStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting-guides': {
      id: '/betting-guides'
      path: '/betting-guides'
      fullPath: '/betting-guides'
      preLoaderRoute: typeof BettingGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-agent': {
      id: '/become-agent'
      path: '/become-agent'
      fullPath: '/become-agent'
      preLoaderRoute: typeof BecomeAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-links': {
      id: '/all-links'
      path: '/all-links'
      fullPath: '/all-links'
      preLoaderRoute: typeof AllLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-blocked': {
      id: '/account-blocked'
      path: '/account-blocked'
      fullPath: '/account-blocked'
      preLoaderRoute: typeof AccountBlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$slug': {
      id: '/matches/$slug'
      path: '/matches/$slug'
      fullPath: '/matches/$slug'
      preLoaderRoute: typeof MatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/toss-market-10-minute-profit': {
      id: '/case-studies/toss-market-10-minute-profit'
      path: '/toss-market-10-minute-profit'
      fullPath: '/case-studies/toss-market-10-minute-profit'
      preLoaderRoute: typeof CaseStudiesTossMarket10MinuteProfitRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/small-budget-betting-strategy': {
      id: '/case-studies/small-budget-betting-strategy'
      path: '/small-budget-betting-strategy'
      fullPath: '/case-studies/small-budget-betting-strategy'
      preLoaderRoute: typeof CaseStudiesSmallBudgetBettingStrategyRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/live-betting-3x-returns': {
      id: '/case-studies/live-betting-3x-returns'
      path: '/live-betting-3x-returns'
      fullPath: '/case-studies/live-betting-3x-returns'
      preLoaderRoute: typeof CaseStudiesLiveBetting3xReturnsRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/ipl-5000-to-25000-profit': {
      id: '/case-studies/ipl-5000-to-25000-profit'
      path: '/ipl-5000-to-25000-profit'
      fullPath: '/case-studies/ipl-5000-to-25000-profit'
      preLoaderRoute: typeof CaseStudiesIpl5000To25000ProfitRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting-guides/how-to-set-betting-limits': {
      id: '/betting-guides/how-to-set-betting-limits'
      path: '/how-to-set-betting-limits'
      fullPath: '/betting-guides/how-to-set-betting-limits'
      preLoaderRoute: typeof BettingGuidesHowToSetBettingLimitsRouteImport
      parentRoute: typeof BettingGuidesRoute
    }
    '/betting-guides/how-to-place-a-live-bet': {
      id: '/betting-guides/how-to-place-a-live-bet'
      path: '/how-to-place-a-live-bet'
      fullPath: '/betting-guides/how-to-place-a-live-bet'
      preLoaderRoute: typeof BettingGuidesHowToPlaceALiveBetRouteImport
      parentRoute: typeof BettingGuidesRoute
    }
    '/betting-guides/how-to-place-a-cricket-bet': {
      id: '/betting-guides/how-to-place-a-cricket-bet'
      path: '/how-to-place-a-cricket-bet'
      fullPath: '/betting-guides/how-to-place-a-cricket-bet'
      preLoaderRoute: typeof BettingGuidesHowToPlaceACricketBetRouteImport
      parentRoute: typeof BettingGuidesRoute
    }
    '/betting-guides/how-to-bet-on-toss-market': {
      id: '/betting-guides/how-to-bet-on-toss-market'
      path: '/how-to-bet-on-toss-market'
      fullPath: '/betting-guides/how-to-bet-on-toss-market'
      preLoaderRoute: typeof BettingGuidesHowToBetOnTossMarketRouteImport
      parentRoute: typeof BettingGuidesRoute
    }
    '/betting-guides/how-to-bet-on-session-betting': {
      id: '/betting-guides/how-to-bet-on-session-betting'
      path: '/how-to-bet-on-session-betting'
      fullPath: '/betting-guides/how-to-bet-on-session-betting'
      preLoaderRoute: typeof BettingGuidesHowToBetOnSessionBettingRouteImport
      parentRoute: typeof BettingGuidesRoute
    }
    '/betting-guides/how-bookmakers-make-money': {
      id: '/betting-guides/how-bookmakers-make-money'
      path: '/how-bookmakers-make-money'
      fullPath: '/betting-guides/how-bookmakers-make-money'
      preLoaderRoute: typeof BettingGuidesHowBookmakersMakeMoneyRouteImport
      parentRoute: typeof BettingGuidesRoute
    }
  }
}

interface BettingGuidesRouteChildren {
  BettingGuidesHowBookmakersMakeMoneyRoute: typeof BettingGuidesHowBookmakersMakeMoneyRoute
  BettingGuidesHowToBetOnSessionBettingRoute: typeof BettingGuidesHowToBetOnSessionBettingRoute
  BettingGuidesHowToBetOnTossMarketRoute: typeof BettingGuidesHowToBetOnTossMarketRoute
  BettingGuidesHowToPlaceACricketBetRoute: typeof BettingGuidesHowToPlaceACricketBetRoute
  BettingGuidesHowToPlaceALiveBetRoute: typeof BettingGuidesHowToPlaceALiveBetRoute
  BettingGuidesHowToSetBettingLimitsRoute: typeof BettingGuidesHowToSetBettingLimitsRoute
}

const BettingGuidesRouteChildren: BettingGuidesRouteChildren = {
  BettingGuidesHowBookmakersMakeMoneyRoute:
    BettingGuidesHowBookmakersMakeMoneyRoute,
  BettingGuidesHowToBetOnSessionBettingRoute:
    BettingGuidesHowToBetOnSessionBettingRoute,
  BettingGuidesHowToBetOnTossMarketRoute:
    BettingGuidesHowToBetOnTossMarketRoute,
  BettingGuidesHowToPlaceACricketBetRoute:
    BettingGuidesHowToPlaceACricketBetRoute,
  BettingGuidesHowToPlaceALiveBetRoute: BettingGuidesHowToPlaceALiveBetRoute,
  BettingGuidesHowToSetBettingLimitsRoute:
    BettingGuidesHowToSetBettingLimitsRoute,
}

const BettingGuidesRouteWithChildren = BettingGuidesRoute._addFileChildren(
  BettingGuidesRouteChildren,
)

interface CaseStudiesRouteChildren {
  CaseStudiesIpl5000To25000ProfitRoute: typeof CaseStudiesIpl5000To25000ProfitRoute
  CaseStudiesLiveBetting3xReturnsRoute: typeof CaseStudiesLiveBetting3xReturnsRoute
  CaseStudiesSmallBudgetBettingStrategyRoute: typeof CaseStudiesSmallBudgetBettingStrategyRoute
  CaseStudiesTossMarket10MinuteProfitRoute: typeof CaseStudiesTossMarket10MinuteProfitRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesIpl5000To25000ProfitRoute: CaseStudiesIpl5000To25000ProfitRoute,
  CaseStudiesLiveBetting3xReturnsRoute: CaseStudiesLiveBetting3xReturnsRoute,
  CaseStudiesSmallBudgetBettingStrategyRoute:
    CaseStudiesSmallBudgetBettingStrategyRoute,
  CaseStudiesTossMarket10MinuteProfitRoute:
    CaseStudiesTossMarket10MinuteProfitRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountBlockedRoute: AccountBlockedRoute,
  AllLinksRoute: AllLinksRoute,
  BasketballRoute: BasketballRoute,
  BecomeAgentRoute: BecomeAgentRoute,
  BettingGuidesRoute: BettingGuidesRouteWithChildren,
  BigWinStoriesRoute: BigWinStoriesRoute,
  BonusRoute: BonusRoute,
  BonusIssuesRoute: BonusIssuesRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  CasinoRoute: CasinoRoute,
  ChampionsTrophyBettingRoute: ChampionsTrophyBettingRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  Cricbet99AppRoute: Cricbet99AppRoute,
  Cricbet99IdRoute: Cricbet99IdRoute,
  Cricbet99Vs11xplayRoute: Cricbet99Vs11xplayRoute,
  Cricbet99VsDiamondExchangeRoute: Cricbet99VsDiamondExchangeRoute,
  Cricbet99VsFairdealRoute: Cricbet99VsFairdealRoute,
  Cricbet99VsGold365Route: Cricbet99VsGold365Route,
  Cricbet99VsLaser247Route: Cricbet99VsLaser247Route,
  Cricbet99VsLotus365Route: Cricbet99VsLotus365Route,
  Cricbet99VsMahavirBookRoute: Cricbet99VsMahavirBookRoute,
  Cricbet99VsReddybookRoute: Cricbet99VsReddybookRoute,
  Cricbet99VsSkyexchange247Route: Cricbet99VsSkyexchange247Route,
  CricketRoute: CricketRoute,
  DemoIdRoute: DemoIdRoute,
  DepositIssuesRoute: DepositIssuesRoute,
  DisclaimerRoute: DisclaimerRoute,
  EsportsRoute: EsportsRoute,
  ExchangeRoute: ExchangeRoute,
  FaqRoute: FaqRoute,
  FootballRoute: FootballRoute,
  HighOddsBettingStrategyRoute: HighOddsBettingStrategyRoute,
  HorseRacingRoute: HorseRacingRoute,
  HowItWorksRoute: HowItWorksRoute,
  HowToDepositRoute: HowToDepositRoute,
  HowToWithdrawRoute: HowToWithdrawRoute,
  IndianCardGamesRoute: IndianCardGamesRoute,
  Ipl2026CalendarRoute: Ipl2026CalendarRoute,
  IplBettingRoute: IplBettingRoute,
  IsCricbet99LegalRoute: IsCricbet99LegalRoute,
  IsCricbet99RealRoute: IsCricbet99RealRoute,
  IsCricbet99SafeRoute: IsCricbet99SafeRoute,
  KabaddiRoute: KabaddiRoute,
  KycPolicyRoute: KycPolicyRoute,
  LoginRoute: LoginRoute,
  LoginIssuesRoute: LoginIssuesRoute,
  OnlineBettingRoute: OnlineBettingRoute,
  PlatformsRoute: PlatformsRoute,
  PoliciesRoute: PoliciesRoute,
  PredictionsRoute: PredictionsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReferralCodeRoute: ReferralCodeRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  ReviewsRoute: ReviewsRoute,
  RulesRoute: RulesRoute,
  ScheduleRoute: ScheduleRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsBettingRoute: SportsBettingRoute,
  SportsIdRoute: SportsIdRoute,
  SupportRoute: SupportRoute,
  T20WorldCupBettingRoute: T20WorldCupBettingRoute,
  TelegramChannelRoute: TelegramChannelRoute,
  TennisRoute: TennisRoute,
  TermsRoute: TermsRoute,
  TodaysBestOddsRoute: TodaysBestOddsRoute,
  TransactionLimitsRoute: TransactionLimitsRoute,
  TrustedBettingAgentRoute: TrustedBettingAgentRoute,
  TrustedBettingIdProviderRoute: TrustedBettingIdProviderRoute,
  WhatIsCricbet99Route: WhatIsCricbet99Route,
  WhatsappNumberRoute: WhatsappNumberRoute,
  WhatsappSupportRoute: WhatsappSupportRoute,
  WhyChooseCricbet99Route: WhyChooseCricbet99Route,
  WithdrawalDelayRoute: WithdrawalDelayRoute,
  Wpl2026BettingRoute: Wpl2026BettingRoute,
  BlogSlugRoute: BlogSlugRoute,
  MatchesSlugRoute: MatchesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
